Add support for MMPBSA binding energy
ChemBioHTP/EnzyHTP pull request #195
Opened 2024-11-07 07:07 UTC by shaoqx

Highlighted new features:
core/
- new function `safe_cp`
- new class `ClusterJobConfig` to unify the cluster_job_config exposed arguments in most science API. (will refactor gradually)

_interface/
- `get_mmpbsa_energy` and related functions
- interface for parmed and mmpbsa.py
- `load_traj` as an easier way to load Amber traj files

analysis/
- `binding_energy`

2024-11-08 05:05 UTC, chrisjurich requested changes
Overall really good. For a loot of the MMPBSA/GBPSA, I didn't really do too much, so make sure it works. The only thing I really have to say is that for the `binding_energy()` api, it may make sense to make it return a `List[float]`

2024-11-08 05:05 UTC, chrisjurich commented on enzy_htp/mutation/api.py
No problem with this change, but what motivated it?

2024-11-08 05:05 UTC, chrisjurich commented on enzy_htp/structure/structure_io/prmtop_io.py
> -    """the parser for Gaussian prmtop files"""
Lol at that typo

2024-11-08 05:42 UTC, shaoqx commented on enzy_htp/analysis/binding.py
> +def binding_energy(
Good idea. I actually have it in the previous version. 
However, it is pretty hard to extract the MMPBSA energy for each frame and will be very slow if we iterate through the stru_esm and run it for each Structure.

2024-11-08 05:52 UTC, shaoqx commented on enzy_htp/mutation/api.py
Because I found when I run scripts that contain this function in parallel to generate random mutations they will always be the same lol. like the same "sequence" of random mutations

2024-11-08 05:52 UTC, shaoqx commented on enzy_htp/_interface/amber_interface.py
lol the reason I didnt finish it in May

2024-11-08 05:53 UTC, shaoqx commented on enzy_htp/analysis/binding.py
> +def binding_energy(
I found some old scripts about it. I will try to do it tomorrow for fun. The hard part is the intermediate files are generated in the current dir.

2024-11-08 07:00 UTC, shaoqx commented on enzy_htp/analysis/binding.py
> +def binding_energy(
Found a workaround from Amber manual

2024-11-08 22:07 UTC, shaoqx commented
Thank you for the comment! I have changed the API to return a list of values for the MMPBSA energy of each frame.

2024-11-08 22:07 UTC, shaoqx commented on enzy_htp/analysis/binding.py
> +def binding_energy(
Just did!

2024-11-09 20:00 UTC, chrisjurich approved these changes
Looks good to me!

2024-11-09 20:50 UTC, merged